#!/bin/bash
# Builds Photocatalog.app: a double-clickable launcher that starts
# `photocatalog serve` (if not already running) and opens the viewer
# in the default browser. Run from anywhere; it locates the project
# root relative to this script.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DEST="${1:-/Applications}"
APP="$DEST/Photocatalog.app"

if [ ! -x "$PROJECT_DIR/.venv/bin/photocatalog" ]; then
  echo "error: $PROJECT_DIR/.venv/bin/photocatalog not found - run the setup steps in README.md first" >&2
  exit 1
fi

if ! mkdir -p "$DEST" 2>/dev/null || [ ! -w "$DEST" ]; then
  echo "error: cannot write to $DEST - pass a writable destination, e.g.:" >&2
  echo "  $0 \"\$HOME/Applications\"" >&2
  exit 1
fi

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>Photocatalog</string>
    <key>CFBundleDisplayName</key>
    <string>Photocatalog</string>
    <key>CFBundleIdentifier</key>
    <string>local.photocatalog.launcher</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleExecutable</key>
    <string>Photocatalog</string>
    <key>LSUIElement</key>
    <true/>
    <key>LSMinimumSystemVersion</key>
    <string>11.0</string>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/Photocatalog" <<LAUNCHER
#!/bin/bash
# Generated by scripts/build_macos_app.sh - do not edit directly, rerun the
# generator instead if PROJECT_DIR or the port needs to change.
PROJECT_DIR="$PROJECT_DIR"
HOST="127.0.0.1"
PORT="5000"
URL="http://\$HOST:\$PORT/"
LOG="/tmp/photocatalog-app.log"

if ! curl -sf "\$URL" -o /dev/null 2>/dev/null; then
  nohup "\$PROJECT_DIR/.venv/bin/photocatalog" serve --host "\$HOST" --port "\$PORT" > "\$LOG" 2>&1 &
  disown
  for _ in \$(seq 1 40); do
    sleep 0.5
    curl -sf "\$URL" -o /dev/null 2>/dev/null && break
  done
fi

open "\$URL"
LAUNCHER

chmod +x "$APP/Contents/MacOS/Photocatalog"

echo "Built $APP"
